### ISSUE TITLE
Dissapearing second level submenu on chrome

### ISSUE THREAD

**Issue by SuchyTheMaster** [BeSite/jQuery.mmenu#298]
Hi.

I have left side pushed mmenu. On left side there are 2 fixed positioned widgets also. Opening menu push whole page (with widgets) and it's great. There shows 1st level menu, but when I click an arrow in any item to show the second level menu, then second level menu doesn't appear. There is animation of slide out (to left) menu level 1, but menu level 2 doesn't show. Moreover, when I close menu and open, then 2nd level is visible. When I launch Chrome Inspector, and change any CSS rule, then level 2 appears and widgets goes under last position of menu (but stil sticked to the page content).

I'm using mmenu with those settings:

```json
{
classes: "mm-slide",
slidingSubmenus: true,
lables: true,
onClick: {
    blockUI: true,
    close: true,
    preventDefault: true,
    setSelected: true},
offCanvas: {
    position: "left",
    zposition: "next"}
}
```

html of widgets:
```html
<div class="floatingWidget">
  <div class="handler">click here</div>
  <div class="content">lorem ipsum...</div>
</div>
```

css of widgets:
```css
.floatingWidget { // whole widget wrapper
position: fixed;
z-index: 1008;
overflow: visible;
height: 0;
width: 0;
left: 0;
top: 120px;
}

.handler { // visible icon of widget (you can click on this to show content)
position: absolute;
left: 0;
top: 0;
width: 60px;
height: 60px;
}

.content { // hidden content of widget (moves from right side, after clicking on handler)
position: absolute;
top: 0;
right: 0
}
```
