### ISSUE TITLE
Difference between 'mm-opened' & 'mm-opening' classes?

### ISSUE THREAD

**Issue by bjzink** [BeSite/jQuery.mmenu#307]
There doesn't seem to be a difference between when the 'mm-opened' and 'mm-opening' classes are added to the html tag. They appear to be added at the same time and as soon as the open trigger is clicked. This doesn't seem right.

Shouldn't the 'mm-opening' class be added during the sliding transition and be removed once the menu is open 100%? And then once the menu is open 100%, shouldn't that be when the 'mm-opened' class is added?

I'm trying to change styles of certain elements during the opening and closing transitions, but I can't target selectors because there's no differentiation in classes between the opening and opened states.

If it is behaving correctly, is there a way to add a class to the html tag during the opening transition only?

Thanks. Love the plugin.

**Comment by FrDH** [comment]
There is a small delay between the two classes, this ensures the menu to animate when opened in front of the page.
````css
.mm-menu {
  // hide the menu
  display: none;
}
.mm-opened {
  // show the menu
  display: block;
  transition: translate3d( -100%, 0, 0 );
}
.mm-opening {
  // animate the menu
  transition: translate3d( 0, 0, 0 );
}
````
Is you need a callback for when the menu is finished opening/closing, have a look at the "opened" and "closed" custom events:
http://mmenu.frebsite.nl/documentation/custom-events.html
