### ISSUE TITLE
My custom close button works unexpectedly. How to fix it? :'(

### ISSUE THREAD

**Issue by durancristhian** [BeSite/jQuery.mmenu#377]
Hi everyone. I'm here looking for some help about how to do something.

I've added a custom close button in the top-right side of the menu. It looks like this:

![screenshot_2015-06-04-15-22-50](https://cloud.githubusercontent.com/assets/4248944/7991552/59807860-0acf-11e5-9b9f-caf17e502173.png)

To do that, I've implemented the following HTML markup:

```javascript
<div id="mnu-mobile">
    <!-- close button -->
    <a class="close-mobile-menu" href="#!">
        <span class="icon-close"></span>
    </a>
    <!-- end of close button -->
    <ul>
        <li>
	    <a href="/">Item</a>
        </li>
```

And the following CSS implementation:

```css
.close-mobile-menu {
	border-left: 1px solid #ccc;
	color: #666;
	line-height: 36px;
	padding: 4px 10px 0;
	position: absolute;
	right: 0;
	top: 0;
	z-index: 100;
}
```

[And obviously the JavaScript that doesn't affect the goal of this issue]

The problem is that, when the menu is big enough to make the vertical scrollbar appears, I get the following result when I scroll down:

![screenshot_2015-06-04-15-25-51](https://cloud.githubusercontent.com/assets/4248944/7991656/334d2336-0ad0-11e5-9d07-0ba22e7e4b96.png)

Apparently, what I supose it's happening it's that for the CSS, the menu (```position: fixed;```) "starts" right there, at top-right of the viewport and I'd like to keep the ```.close-mobile-menu``` near the title, near the first element, that's hidden by the scrolling process now.

I don't know if I'm clear. Maybe, I'm losing something.
What do you think?
