### ISSUE TITLE
Button to open AND close the menu

### ISSUE THREAD

**Issue by vincentvandergraaff** [BeSite/jQuery.mmenu#401]
I want to open and close the bottom_menu with the same button. I really don't know how to do this. 

I open the menu with the link #menu but when i click on this link when the menu is open, the menu didn't close.

Has anyone an idea?

**Comment by FrDH** [comment]
Any anchor that links to the page will automatically close the menu when clicked:
````html
<a href="#page">
<div id="page">
````
You could go with that I guess.

**Comment by vincentvandergraaff** [comment]
Thanks FrDH, but this didn't work. The button won't open the menu if i navigate on the page.

**Comment by FrDH** [comment]
This anchor will open the menu (assuming your menu has `id="menu"`)
````html
<a href="#menu">open menu</a>
````
This anchor will close the menu (assuming your page has `id="page"`)
````html
<a href="#page">close menu</a>
````

You can use CSS to toggle the anchors visibility when the menu is closed/opened:
````css
a[href="#menu"] { display: block; }
a[href="#page"] {  display: none; }
html.mm-opened a[href="#menu"] {  display: none;  }
html.mm-opened a[href="#page"] {  display: block;  }
````

I guess you could also manually code the button to trigger the menu to open close using the API:
http://mmenu.frebsite.nl/documentation/api.html
