### ISSUE TITLE
Visible on load (full screen) not working?

### ISSUE THREAD

**Issue by alvarotrigo** [BeSite/jQuery.mmenu#450]
I'm trying to copy the [example you provided](http://mmenu.frebsite.nl/demo/index.html?demo=app-settings), but I can't manage to make the menu visible onload.
[Reproduction online](http://jsfiddle.net/LgLmmofn/)

**Comment by alvarotrigo** [comment]
Ok, found the problem.
You are using your own styles to get the full screen effect. This is not something the plugin does it by itself.

I solved it adding the following ones which I managed to extract from your "demo.css" file.

```css
html, body {
    height: 100%;
}
#mmenu,
.menu-wrapper{
    min-width: none;
    max-width: none;
    width: 100%;
    height: 100%;
}
```

I believe this should be more clear in the docs in any case.
