### ISSUE TITLE
Is it possible adding html content after mm-panels?

### ISSUE THREAD

**Issue by bardpresent** [BeSite/jQuery.mmenu#470]
Well I want to add my own content next to the mm-panels, but not in the bottom like the social icons in the bottom.
I couldn't find an extension for this.

**Comment by FrDH** [comment]
There currently is no extension for this, I guess it wouldn't be hard to expand the "navbars" add-on to support navbars on the left and/or right, but for now I guess you can add HTML manually after the plugin fired:
````javascript
$("#my-menu").mmenu();
$("#my-menu").append( '<div id="my-left-panel">other content</div>' );
````
Adding some small CSS should make things work:
````css
.mm-panels {
    left: 40px;
}
#my-left-panel {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    width: 40px;
}
````
